ASP/WineShop/WineShop/WineShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WineShop.Models;
using WineShop.Services;

namespace WineShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IArdoaService _ardoaService;

        public HomeController(ILogger<HomeController> logger, IArdoaService ardoaService)
        {
            _logger = logger;
            _ardoaService = ardoaService;
        }

        public async Task<IActionResult> Index()
        {
            List<Ardoa> ardoaList = new List<Ardoa>();
            ardoaList = await _ardoaService.GetArdoak();
            return View(ardoaList.Where(a => a.Eskaintza == true));
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP/WineShop/WineShop/WineShop/Controllers/SaskiaController.cs
using Microsoft.AspNetCore.Mvc;
using WineShop.Models;
using WineShop.Services;
using WineShop.ViewModels;

namespace WineShop.Controllers
{
    public class SaskiaController : Controller
    {
        private readonly ISaskiaService _saskiaService;
        private readonly IArdoaService _ardoaService;
        public SaskiaController(ISaskiaService saskiaService, IArdoaService ardoaService)
        {
            _saskiaService = saskiaService;
            _ardoaService = ardoaService;
        }
        public async Task<IActionResult> Index(string id)
        {
            IList<SaskiaAlea> saskiaAleaList = new List<SaskiaAlea>();
            saskiaAleaList = await _saskiaService.SaskiaLortuAleak(id);
            //Ardo bakoitzaren datuak hartu eta ViewModel bezala sortu
            IList<SaskiaAleaViewModel> saskiaAleaVMList = new List<SaskiaAleaViewModel>();
            foreach (var saskiaAlea in saskiaAleaList)
            {
                var ardoa = await _ardoaService.GetArdoa(saskiaAlea.ArdoaId);
                SaskiaAleaViewModel saskiaAleaViewModel = new SaskiaAleaViewModel()
                {
                    ArdoaId = ardoa.Id,
                    Irudia = ardoa.Irudia,
                    Izena = ardoa.Izena,
                    Kantitatea = saskiaAlea.Kantitatea,
                    Salneurria = ardoa.Salneurria
                };
                saskiaAleaVMList.Add(saskiaAleaViewModel);
            }
            var saskiaViewModel = new SaskiaViewModel(); //Bistaratuko dugun ViewModel osoa
            saskiaViewModel.SaskiaAleaVMList = saskiaAleaVMList;
            return View(saskiaViewModel);
        }
        public async Task<IActionResult> SaskiaGehitu(int id)
        {
            var cart = Saskia.SaskiaLortu(this.HttpContext); //aurretik sortu dugun Saskia klasea erabiliz
            await _saskiaService.SaskiaGehitu(id, cart.SaskiaId); //zerbitzu berrian karritoan gehitzeko
            return RedirectToAction("Index", new { id = cart.SaskiaId });
        }
        public async Task<IActionResult> SaskiaGehituAjax(int id, int kantitatea, float salneurria, float guztira)
        {
            var cart = Saskia.SaskiaLortu(this.HttpContext);
            await _saskiaService.SaskiaGehitu(id, cart.SaskiaId);
            kantitatea++;
            var results = new
            {
                mezua = "Zure saskia eguneratu da",
                kantitatea = kantitatea,
                salneurria = salneurria,
                guztira = guztira
            };
            return Json(results);
        }

    }
}

ASP/WineShop/WineShop/WineShop/ViewComponents/ArdoakViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WineShop.Services;

namespace WineShop.ViewComponents
{
    public class ArdoakViewComponent : ViewComponent
    {
        private readonly IArdoaService _ardoaService;
        public ArdoakViewComponent(IArdoaService ardoaService)
        {
            _ardoaService = ardoaService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            ViewBag.mota = id;
            return View(await _ardoaService.GetMota(id));
        }
    }
}

ASP/WineShop/WineShop/WineShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<nav class="navbar navbar-expand-lg navbar-light bg-light bg-menua">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse erlatiboa" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item dropdown full-width">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Zuria
                    </a>
                    @await Component.InvokeAsync("Ardoak", new { id = 1 })

                </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item dropdown full-width">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Beltza
                    </a>
                    @await Component.InvokeAsync("Ardoak", new { id = 2 })
                </li>
            </ul>
        </div>
    </div>
</nav>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" arialabel="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/images/banner1.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/banner2.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/banner3.jpg" alt="Third slide">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h4 class="borgona">
                Gure Eskaintzak:
            </h4>
        </div>
        <div class="col-md-3">
            <!-- Controls -->
            <div class="controls pull-right hidden-xs">
                <a class="left fa fa-chevron-left btn btn-success" href="#carousel-example"
                   data-bs-slide="prev"></a><a class="right fa fa-chevron-right btn btn-success" href="#carousel-example"
                                            data-bs-slide="next"></a>
            </div>
        </div>
    </div>
    <div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            @{var itemLerroko = 0;
                var fila1 = false;}

            @{
                foreach (var item in Model)
                {
                    if (itemLerroko == 0)
                    {
                        if (fila1 == false)
                        {
                            @:<div class="carousel-item active">
                                @:    <div class="row">
                                }
                                else
                                {
                                    @:<div class="carousel-item">
                                        @:    <div class="row">
                                        }
                                    }


                                    <div class="col-sm-3">
                                        <div class="col-item">
                                            <div class="photo text-center">
                                                <img class="irudia" src="~/images/ardoak/@item.Irudia" alt="a" />
                                            </div>
                                            <div class="info">
                                                <div class="row">
                                                    <div class="price col-md-6">
                                                        <h5>
                                                            @item.Deskribapena
                                                        </h5>

                                                        <span class="tachado">@item.Salneurria</span>
                                                        %@item.Deskontua
                                                        @{ decimal eskaintza = item.Salneurria - (item.Salneurria * item.Deskontua) / 100;}
                                                        <h5 class="price-text-color">
                                                            @eskaintza
                                                        </h5>
                                                    </div>
                                                    <div class="rating d-sm-none d-md-block col-md-6">
                                                        <i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                        </i><i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                        </i><i class="fa fa-star"></i>
                                                    </div>
                                                </div>
                                                <div class="separator clear-left">
                                                    <p class="btn-details">
                                                        <i class="fa fa-list"></i><a href="http://www.jquery2dotnet.com" class="d-sm-none d-md-block">Detaile gehiago</a>
                                                    </p>
                                                        <p class="btn-add">
                                                        <i class="fa fa-shopping-cart"></i>
                                                        <a asp-controller="Saskia" asp-action="SaskiaGehitu" asp-route-id="@item.Id">Karritora gehitu</a>
                                                    </p>
                                                </div>
                                                <div class="clearfix">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    itemLerroko++;
                                    fila1 = true;
                                    if (itemLerroko > 3)
                                    {
                                    @:</div>
                                @:</div>
                                itemLerroko = 0;
                            }

                        }
            }

        </div>
    </div>
</div>
</div>
</div>