ASP/WineShop/WineShop/WineShop/ViewModels/SaskiaViewModel.cs
namespace WineShop.ViewModels
{
    public class SaskiaViewModel
    {
        public IList<SaskiaAleaViewModel> SaskiaAleaVMList { get; set; }
    }

}

ASP/WineShop/WineShop/WineShop/Controllers/OrdainduController.cs
using Microsoft.AspNetCore.Authorization;
using WineShop.Services;
using Microsoft.AspNetCore.Mvc;
using WineShop.Models;
using WineShop.ViewModels;

namespace WineShop.Controllers
{
    [Authorize]
    public class OrdainduController : Controller
    {
        private readonly ISaskiaService _saskiaService;
        public OrdainduController(ISaskiaService saskiaService)
        {
            _saskiaService = saskiaService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Abizena,Helbidea,Herrialdea,Hiria,Izena,Postakodea,Telefonoa")]
BezeroaEskaera bezeroaEskaera)
        {
            if (ModelState.IsValid)
            {
                /*Bezeroen datuak gorde*/
                bezeroaEskaera.Erabiltzailea = HttpContext.User.Identity.Name;
                bezeroaEskaera.Data = DateTime.Now;
                await _saskiaService.EskaeraBezeroaGehitu(bezeroaEskaera);
                /*Eskaera gorde*/
                var cart = Saskia.SaskiaLortu(this.HttpContext);
                await _saskiaService.EskaeraSortu(bezeroaEskaera, cart.SaskiaId);
                /*Beste pantaila batera berbideratzen da*/
                return RedirectToAction("Osatu", new
                {
                    bezeroa = bezeroaEskaera.Izena + " " + bezeroaEskaera.Abizena,
                    saskiaId = cart.SaskiaId
                });
            }
            return View(bezeroaEskaera);
        }
        public async Task<IActionResult> Osatu(string bezeroa, string saskiaId)
        {
            var osatuViewModel = new OsatuViewModel(); //ViewModel bat erabiliko dugu
            osatuViewModel.SaskiaAleak = await _saskiaService.SaskiaLortuAleak(saskiaId);
            osatuViewModel.SaskiaId = saskiaId;
            osatuViewModel.Bezeroa = bezeroa;
            return View(osatuViewModel);
        }
    }
}

ASP/WineShop/WineShop/WineShop/Controllers/SaskiaController.cs
using Microsoft.AspNetCore.Mvc;
using WineShop.Models;
using WineShop.Services;
using WineShop.ViewModels;

namespace WineShop.Controllers
{
    public class SaskiaController : Controller
    {
        private readonly ISaskiaService _saskiaService;
        private readonly IArdoaService _ardoaService;
        public SaskiaController(ISaskiaService saskiaService, IArdoaService ardoaService)
        {
            _saskiaService = saskiaService;
            _ardoaService = ardoaService;
        }
        public async Task<IActionResult> Index(string id)
        {
            IList<SaskiaAlea> saskiaAleaList = new List<SaskiaAlea>();
            saskiaAleaList = await _saskiaService.SaskiaLortuAleak(id);
            //Ardo bakoitzaren datuak hartu eta ViewModel bezala sortu
            IList<SaskiaAleaViewModel> saskiaAleaVMList = new List<SaskiaAleaViewModel>();
            foreach (var saskiaAlea in saskiaAleaList)
            {
                var ardoa = await _ardoaService.GetArdoa(saskiaAlea.ArdoaId);
                SaskiaAleaViewModel saskiaAleaViewModel = new SaskiaAleaViewModel()
                {
                    ArdoaId = ardoa.Id,
                    Irudia = ardoa.Irudia,
                    Izena = ardoa.Izena,
                    Kantitatea = saskiaAlea.Kantitatea,
                    Salneurria = ardoa.Salneurria
                };
                saskiaAleaVMList.Add(saskiaAleaViewModel);
            }
            var saskiaViewModel = new SaskiaViewModel(); //Bistaratuko dugun ViewModel osoa
            saskiaViewModel.SaskiaAleaVMList = saskiaAleaVMList;
            return View(saskiaViewModel);
        }
        public async Task<IActionResult> SaskiaGehitu(int id)
        {
            var cart = Saskia.SaskiaLortu(this.HttpContext); //aurretik sortu dugun Saskia klasea erabiliz
            await _saskiaService.SaskiaGehitu(id, cart.SaskiaId); //zerbitzu berrian karritoan gehitzeko
            return RedirectToAction("Index", new { id = cart.SaskiaId });
        }
        public async Task<IActionResult> SaskiaGehituAjax(int id, int kantitatea, float salneurria, float guztira)
        {
            var cart = Saskia.SaskiaLortu(this.HttpContext);
            await _saskiaService.SaskiaGehitu(id, cart.SaskiaId);
            kantitatea++;
            var results = new
            {
                mezua = "Zure saskia eguneratu da",
                kantitatea = kantitatea,
                salneurria = salneurria,
                guztira = guztira
            };
            return Json(results);
        }

    }
}

ASP/WineShop/WineShop/WineShop/Views/Saskia/Index.cshtml
@using System.Globalization;
@model WineShop.ViewModels.SaskiaViewModel;
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div id="update-message"></div>
    <table class="table table-striped">
        <thead>
            <tr class="borgona">
                <th>Izena</th>
                <th>Irudia</th>
                <th>Kantitatea</th>
                <th>Salneurria</th>
                <th>Guztira</th>
            </tr>
        </thead>
        @{
            decimal saskiaguztira = 0;
        }
        @foreach (var item in Model.SaskiaAleaVMList)
        {
            <tr id="row-@item.ArdoaId">
                <td>
                    @item.Izena
                </td>
                <td>
                    <img class="img-thumbnail altuera" id="thumbnail" src="~/images/ardoak/@item.Irudia" />
                </td>
                <td>
                    @*@item.Kantitatea*@
                    <div>
                        <a href="" class="RemoveLink" data-id="@item.ArdoaId">
                            <i class="fas fa-cart-arrow-down"></i>
                        </a>
                        <span id="item-count-@item.ArdoaId">@item.Kantitatea</span>
                        <a href="" class="AddLink" data-id="@item.ArdoaId" data-kantitatea="@item.Kantitatea" data-salneurria="@item.Salneurria">
                            <i class="fas fa-cart-plus"></i>
                        </a>
                    </div>
                </td>
                <td>
                    @item.Salneurria
                </td>
                <td>
                    @{
                        decimal guztira = item.Salneurria * item.Kantitatea;
                        saskiaguztira += guztira;
                    }
                    @guztira
                </td>
            </tr>
        }
        <tr>
            <td>
                <a class="btn btn-borgona text-light" asp-controller="Home" asp-action="Index">Bueltatu</a>
                <a class="btn btn-borgona text-light" asp-controller="Ordaindu" asp-action="Index">Ordaindu</a>
            </td>
            <td></td>
            <td></td>
            <td class="float-right"><p>Guztira: <span id="cart-total">@saskiaguztira.ToString("C2", CultureInfo.CurrentCulture)</span></p></td>
        </tr>
    </table>
</div>